### ISSUE TITLE
native build fails

### ISSUE THREAD

**Issue by jnsfrg** [dovidio/quarkus-jdbc-sqlite#1]
Hi,

did you ever got this to work? We are currently working on a similar extension and came across your repo. But we ran into issues building this in native mode. 
Did you supply any additional Build args not listed in the repo e.g. in the App that includes the extension? 

Builds always fail like this: 
```bash 
...
[total]: 587,008.39 ms,  3.74 GB
 Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
       at parsing org.sqlite.BusyHandler.<init>(BusyHandler.java:10)
       at method: void org.sqlite.BusyHandler.<init>()
       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2624)
      at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:107)
...
```
Maybe you can give a little hint that would be awesome!

**Comment by dovidio** [comment]
Hi, I have added an example application on how to use this extension. I was able to compile it natively using the command
```bash
mvn package  -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
``` on ubuntu 20.04 using the docker build.
Note that this is running a quite old quarkus version, with newer quarkus versions there is most likely some work to do
